[IV-21-22] Objetivo 2
edusegrich/OpoTests pull request #19
Opened 2021-10-24 18:12 UTC by aleveji

PR para llevar a cabo el Objetivo 2 del proyecto de IV.
Para ello estoy trabajando sobre los issues #17, #18, #24, #25, #26, #27 y #28 que se cerrarán al aceptar el PR.

Closes #17, #18, #24, #25, #26, #27, #28

2021-10-30 20:59 UTC, edusegrich commented
@aleveji aprobado, puedes hacer el PR al repo general.

2021-10-31 21:36 UTC, edusegrich approved these changes
@JJ listo para revisión.

2021-11-05 10:48 UTC, JJ requested changes
Por favor, revisad el guión de este objetivo
1. Ni un solo commit se refiere a ningún issue
2. Este PR no está asignado a ningún milestone
3. El objetivo #17 no era necesario, pero si lo es tiene que cerrarse desde código. ¿Hay algún fichero de configuración donde se ponga el lenguaje? Pues eso.
4. Closes hay que ponerlo delante de cada cosa que se cierre. Y por supuesto justificarlo, no ponerlo a jopo.
5. Ni un sólo commit explica lo que hace, se limita a repetir lo que es evidente, que ha modificado no sé qué fichero.
6. El issue #18 ni siquiera se refiere a ninguna historia de usuario. Es imposible saber qué programar ni qué restricciones tiene con eso.

2021-11-05 10:48 UTC, JJ commented on iv.yaml
> +entidad: opotests/Oposicion.py
Esto está mal, además de copiado (y se explicó en clase que estaba mal)

2021-11-08 18:15 UTC, aleveji commented
Listo para revisión @edusegrich y @JJ

2021-11-09 12:20 UTC, JJ requested changes
Os agradecería que siguiérais la lista de comprobación de este objetivo  (y de los anteriores) y que no lo pongáis listo para revisión hasta que no hayáis corregido todo lo que se pone. También a @edusegrich le aconsejaría que supervisara de una forma un poco más precisa el desarrollo de su proyecto.

2021-11-09 12:20 UTC, JJ commented on opotests/Oposicion.py
> +        self.descripcion = descripcion
¿De veras @edusegrich que la descripción es necesaria para la lógica de negocio? ¿Las oposiciones tienen sólo un título? ¿No tienen, no sé, una fecha?

2021-11-09 12:20 UTC, JJ commented on opotests/Pregunta.py
> +        self.id = id
Aunque a priori no parece que haya ningún problema con esta clase, se ha creado con un solo commit, que no hace referencia a ningún issue y por tanto a ninguna HU. Es imposible saber si está bien, o mal, o necesita algo más, o algo menos, o necesita alguna función en el interfaz (no hay ninguna), o todos los atributos son públicos o privados (no siguen ninguna convención) ni en realidad sigue ninguna regla de desarrollo ágil. @edusegrich deberías haber hecho algún tipo de objeción. Por ejemplo, , dificultad ¿qué es? ¿Fácil, difícil, no la aprueba nadie? ¿No será quizás un enum?

2021-11-09 12:20 UTC, JJ commented on opotests/Tema.py
> +        self.id = id
¿Va a haber dos temas con el mismo título? ¿Si lo hay, no será porque son de dos oposiciones diferentes? Por supuesto, mismo problema que las otras: un solo commit, mensaje sin información real, no issue, y demás.

2021-11-09 13:26 UTC, edusegrich commented on opotests/Oposicion.py
> +        self.descripcion = descripcion
Es cierto que la descripción no es algo relevante para la lógica de negocio. La fecha de la oposición (o de la convocatoria) sí podría ser de utilidad para la lógica de negocio, sobre todo en [HU3](https://github.com/edusegrich/OpoTests/issues/7) y [HU4](https://github.com/edusegrich/OpoTests/issues/8).

No había indicado ninguna información más a las oposiciones porque he considerado que el elemento que mejor define una oposición para la lógica de negocio son los temas que la componen. Aún así, un atributo que podría ser interesante añadir es el [*Grupo de Clasificación*](https://www.doncursos.com/grupos-de-clasificacion-y-funciones-de-los-funcionarios.html).

2021-11-09 13:26 UTC, edusegrich commented on opotests/Pregunta.py
> +        self.id = id
El atributo 'dificultad' puede ser Alto, Medio o Bajo (especificado en #12). Por tanto, debería ser un enum.

2021-11-09 13:26 UTC, edusegrich commented on opotests/Tema.py
> +        self.id = id
No. No hay dos temas con el mismo título. Puede haber temas que tengan un título parecido pero con matices que los hacen diferentes.

2021-11-09 13:26 UTC, edusegrich commented
Me dispongo a concretar las issues teniendo en cuenta la [lista de comprobación del objetivo 2](http://jj.github.io/IV/documentos/proyecto/2.Entidad#lista-de-comprobaci%C3%B3n) y, a continuación, especificar las correcciones que debe llevar a cabo @aleveji en el desarrollo de proyecto.

2021-11-10 00:34 UTC, edusegrich commented
A continuación te adjunto, @aleveji, las correcciones que debes hacer en el desarrollo del proyecto.

1. La descripción en las **oposiciones** es innecesaria para la lógica de negocio, hay que suprimirla. En su lugar, se añadirá la fecha de la convocatoria (un *String* con el formato **dd/mm/yyyy**, por ejemplo) y una [*clasificación*](https://www.doncursos.com/grupos-de-clasificacion-y-funciones-de-los-funcionarios.html) que podrá ser A1, A2, B, C1, C2 o E. En #21 se aporta la información más detallada.
2. **No existirán** dos temas con el mismo *título*, por tanto, el atributo *Id* es innecesario. La explicación te la especifico en #22.
3. El punto anterior también se aplica para las **oposiciones** (#21).
4. El atributo *dificultad* de la clase *Pregunta* solo puede tomar uno de entre estos valores: **Alto**, **Medio** y **Bajo** (tal y como se especifica en #12). Por tanto, este debe ser representado con un **enumerado**.
5. Establece la visibilidad de los atributos de las clases como **privada** e intenta añadir los *getters* correspondientes.
6. Incluye en la clase Oposición:
    - Función para añadir un tema (tipo *add_tema(tema)*, o algo del estilo).
En la clase Pregunta:
    - Función para añadir una respuesta (tipo *add_respuesta(respuesta)*, o algo del estilo).

Estas funciones, ya que no tenemos tests de comprobación todavía, no necesitan tener implementación, simplemente *hacen pass*. Te dejo un ejemplo [aquí](https://github.com/JJ/curso-tdd/blob/master/temas/dise%C3%B1o.md#ejemplo).
7. Guía sobre qué tener en cuenta a la hora de escribir un commit [aquí](https://www.theserverside.com/video/Follow-these-git-commit-message-guidelines). Describe en ellos *qué* haces y *por qué*, pero no el *cómo*.

Cuando lo tengas mencióname solo a mí para que hagamos las comprobaciones antes de pedírselo a JJ.

2021-11-14 20:19 UTC, aleveji commented
Listo para revisión @edusegrich :smile:

2021-11-15 16:54 UTC, edusegrich commented
Creo que has hecho buen trabajo, @aleveji. Lo único que debes corregir es el nombre de los ficheros, para que sean *all-lowercase* (todo en minúscula). Recuerda cambiarlo también en los "imports" en el código y en el ".yaml". En cuanto lo tengas mencionamos a JJ.

2021-11-15 17:21 UTC, aleveji commented
Hecho @edusegrich

2021-11-15 17:31 UTC, edusegrich commented
Listo para revisión @JJ

2021-11-18 09:16 UTC, JJ approved these changes
:+1:

2021-11-19 11:37 UTC, merged