[IV-21-22] Objetivo 3
edusegrich/OpoTests pull request #30
Opened 2021-11-30 13:19 UTC by edusegrich

PR para el Objetivo 3.
Se ha realizado la elección de **Poetry** como gestor de dependencias e **Invoke** como gestor de tareas para #29.

2021-11-30 13:26 UTC, edusegrich commented
@JJ listo para revisión.

2021-12-01 08:45 UTC, JJ requested changes
Una justificación de una elección de una herramienta no es comunicación de una decisión. Es mostrar que se conocen qué herramientas hay, y que se han establecido unos criterios para elegir una determinada. Por lo demás, mira la lista de comprobación correspondiente y comprueba si la has seguido.

2021-12-01 08:45 UTC, JJ commented on README.md
> +Lo primero que debes hacer es [instalar Poetry](https://python-poetry.org/docs/#installation), el gestor de dependencias del proyecto. Para ello, abre una terminal y ejecuta el siguiente comando:
Para copiar las instrucciones de Poetry, que están en 5 o 6 READMEs, simplemente enlazadlas.

2021-12-01 08:45 UTC, JJ commented on docs/justificacion_gestor_tareas.md
> +# Elección Gestor de Tareas Invoke
Aparte de que es el que ha elegido todo el mundo, ¿hay alguna justificación más? ¿Qué otras opciones hay?

2021-12-02 09:05 UTC, edusegrich commented
@JJ listo para revisión.

2021-12-05 19:47 UTC, JJ approved these changes
En general está bien y el objetivo alcanzado, pero corrige todo lo dicho antes del siguiente.

2021-12-05 19:47 UTC, JJ commented on README.md
> +El siguiente paso es  [instalar Poetry](https://python-poetry.org/docs/#installation), el **gestor de dependencias** del proyecto. Para instalarlo, sitúate en el directorio raíz del proyecto y ejecut
Sería bastante mejor que instalaras Poetry primero, que es el gestor de dependencias, y luego invoke, que es una dependencia, desde él. El gestor de tareas no lo puedes instalar hasta que no tengas las tareas...

2021-12-05 19:47 UTC, JJ commented on README.md
> +invoke installpoetry
Bueno, también es una opción...

2021-12-05 19:47 UTC, JJ commented on README.md
> +invoke installdependencies
`installdeps` suele ser el target usado

2021-12-05 19:47 UTC, JJ commented on README.md
> +invoke syntax
`check` es el target que se ha dicho.

2021-12-05 19:47 UTC, JJ commented on README.md
> +##### Usuarios 🧑‍🤝‍🧑
Agh, ¿por qué hacéis esto?

2021-12-05 19:47 UTC, JJ commented on tasks.py
> +    run("pylint -E opotests")
Este target sería "lint", no "check".

2021-12-10 12:37 UTC, merged